apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: cert-manager-config
    namespace: flux-system
spec:
    dependsOn:
        - name: flux-system
    path: ./cluster/core/cert-manager/config
    prune: true
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: external-dns-config
    namespace: flux-system
spec:
    dependsOn:
        - name: flux-system
    path: ./cluster/core/external-dns/config
    prune: true
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: samba-config
    namespace: flux-system
spec:
    dependsOn:
        - name: flux-system
    path: ./cluster/core/samba/config
    prune: true
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: authentik-config
    namespace: flux-system
spec:
    dependsOn:
        - name: flux-system
    path: ./cluster/core/authentik/config
    prune: true
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
    name: external-external-config
    namespace: flux-system
spec:
    dependsOn:
        - name: flux-system
    path: ./cluster/core/external-secrets/config
    prune: true
    interval: 5m
    sourceRef:
        kind: GitRepository
        name: flux-system
