---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: grafana
    namespace: authentik
spec:
    hostnames:
        - grafana.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: prometheus
    namespace: authentik
spec:
    hostnames:
        - prometheus.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: alertmanager
    namespace: authentik
spec:
    hostnames:
        - alertmanager.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: hubble
    namespace: authentik
spec:
    hostnames:
        - hubble.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: firefly
    namespace: authentik
spec:
    hostnames:
        - firefly.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: syncthing
    namespace: authentik
spec:
    hostnames:
        - syncthing.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: jellyfin
    namespace: authentik
spec:
    hostnames:
        - jellyfin.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
    name: qbittorrent
    namespace: authentik
spec:
    hostnames:
        - qbittorrent.k8s.home.lab
    parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: main-gateway
          namespace: gateway
    rules:
        - matches:
              - path:
                    type: PathPrefix
                    value: /
          backendRefs:
              - name: ak-outpost-authentik-embedded-outpost
                port: 9000
