apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gateway
  - flux-system
  - cert-manager
  - external-secrets
  - external-dns
  - nfs
  - samba
  - cloudpg
  - authentik
  - monitoring
