apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: vault-issuer
spec:
  vault:
    server: http://192.168.1.48:8200
    path: pki_int/issue/k8s-cluster-role
    auth:
      kubernetes:
        mountPath: auth/kubernetes
        role: cert-manager-role
        serviceAccountRef:
          name: cert-manager
