---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jellyfin-media-smb
    namespace: jellyfin
spec:
    accessModes:
        - ReadOnlyMany
    storageClassName: smb-csi
    resources:
        requests:
            storage: 1Gi
