apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: shared-postgres-credentials
  namespace: database
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: shared-postgres-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: "shared"
        password: "{{ .password }}"
  data:
  - secretKey: password
    remoteRef:
      key: database/shared
      property: password
